[2025-04-29T06:20:02.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T06:20:04.214+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:20:04.762+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T06:13:49.675488+00:00 [queued]>
[2025-04-29T06:20:04.767+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-29T06:20:06.620+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): prepare_data> on 2025-04-29 06:13:49.675488+00:00
[2025-04-29T06:20:06.716+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'all_classification_pipeline', 'prepare_data', 'manual__2025-04-29T06:13:49.675488+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/classification_pipeline.py', '--cfg-path', '/tmp/tmpvdt2_gqr']
[2025-04-29T06:20:06.675+0000] {standard_task_runner.py:72} INFO - Started process 797 to run task
[2025-04-29T06:20:06.830+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask prepare_data
[2025-04-29T06:20:10.058+0000] {task_command.py:467} INFO - Running <TaskInstance: all_classification_pipeline.prepare_data manual__2025-04-29T06:13:49.675488+00:00 [running]> on host 6654e0e8303a
[2025-04-29T06:20:13.310+0000] {job.py:229} INFO - Heartbeat recovered after 14.35 seconds
[2025-04-29T06:20:14.852+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='all_classification_pipeline' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T06:13:49.675488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-29T06:13:49.675488+00:00'
[2025-04-29T06:20:14.918+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T06:20:17.555+0000] {logging_mixin.py:190} INFO - Wrote 2604 rows to /opt/data/processed_manifest/train.csv
[2025-04-29T06:20:17.637+0000] {logging_mixin.py:190} INFO - Wrote 326 rows to /opt/data/processed_manifest/val.csv
[2025-04-29T06:20:17.811+0000] {logging_mixin.py:190} INFO - Wrote 326 rows to /opt/data/processed_manifest/test.csv
[2025-04-29T06:20:17.831+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-29T06:20:18.104+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T06:20:18.117+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=all_classification_pipeline, task_id=prepare_data, run_id=manual__2025-04-29T06:13:49.675488+00:00, execution_date=20250429T061349, start_date=20250429T062004, end_date=20250429T062018
[2025-04-29T06:20:19.903+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T06:20:20.304+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-29T06:20:20.402+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
